### ISSUE TITLE
https://www.google.com/#q=name not working

### ISSUE THREAD

**Issue by bumaociyuan** [brabidou/fix-google-link-colors#1]
Hi @brabidou 
Very nice work, thank you.

But https://www.google.com/#q=name is not working , can you fix it?

**Comment by 7477** [comment]
You have to change it to your country:

default is google.com

for me it was .at I am from Austria
// @match        https://www.google.at/search*
// @match        http://www.google.at/search*

so change it, to whatever the google version of your country is.

**Comment by dcanl** [comment]
Hi,

Same problem for me : search url format is https://www.google.fr/#q=(search terms), but inserting this rule at the top of the script doesn't work, no script recognized by TamperMonkey (using Chrome)...

Note that "#q=" can be somewhere else in the url (depending of the way to access to the search page), so the pattern would be https://www.google.fr/*#q=* 

I don't understand why the script doesn't match the rule... Any idea ?

**Comment by brabidou** [comment]
I widened the mach query. Now I'm using .tld which should match any language and removed the "search" part of the url

Try updating.
